// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7MQgbQRQ534o6XxyPt9dmJuVgfTnueLU',
    appId: '1:886195786211:web:79be297c37525a34c7d0d6',
    messagingSenderId: '886195786211',
    projectId: 'farxada114-94ff1',
    authDomain: 'farxada114-94ff1.firebaseapp.com',
    storageBucket: 'farxada114-94ff1.firebasestorage.app',
    measurementId: 'G-C9PFFDC21F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWDVg3G1A7vo7-pv1jCWcQmv9zN0-EYqM',
    appId: '1:886195786211:android:ddab50169d67fcb4c7d0d6',
    messagingSenderId: '886195786211',
    projectId: 'farxada114-94ff1',
    storageBucket: 'farxada114-94ff1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu2j3c9uud4c2jLC2W_4aA6hHqzbEvsE0',
    appId: '1:886195786211:ios:9e067288d2db59dcc7d0d6',
    messagingSenderId: '886195786211',
    projectId: 'farxada114-94ff1',
    storageBucket: 'farxada114-94ff1.firebasestorage.app',
    iosBundleId: 'com.farxada.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu2j3c9uud4c2jLC2W_4aA6hHqzbEvsE0',
    appId: '1:886195786211:ios:9e067288d2db59dcc7d0d6',
    messagingSenderId: '886195786211',
    projectId: 'farxada114-94ff1',
    storageBucket: 'farxada114-94ff1.firebasestorage.app',
    iosBundleId: 'com.farxada.app',
  );
}
