// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHYBpr8-C8llMttHsW-Gi_3MAmaUISlfM',
    appId: '1:759730002001:web:31cf9f4387a21415a80070',
    messagingSenderId: '759730002001',
    projectId: 'haldoor-6c091',
    authDomain: 'haldoor-6c091.firebaseapp.com',
    storageBucket: 'haldoor-6c091.firebasestorage.app',
    measurementId: 'G-2MHQJ5CERX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRb62gy2rf03xZ7rM-C91KjAFeHW13XIA',
    appId: '1:759730002001:android:20a75d1067b529a4a80070',
    messagingSenderId: '759730002001',
    projectId: 'haldoor-6c091',
    storageBucket: 'haldoor-6c091.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbx_MU3rXvZvsymWqJU3rxRSd0x4o-8pg',
    appId: '1:759730002001:ios:ab5567d3bfb2b047a80070',
    messagingSenderId: '759730002001',
    projectId: 'haldoor-6c091',
    storageBucket: 'haldoor-6c091.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );
}
