// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsJDf_YtNJo_ypckNB3TOOHgw3M9q8wuc',
    appId: '1:375449913411:web:b712493b99bc5097b0ecf6',
    messagingSenderId: '375449913411',
    projectId: 'faraxda',
    authDomain: 'faraxda.firebaseapp.com',
    storageBucket: 'faraxda.firebasestorage.app',
    measurementId: 'G-CYCJM39QKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS8N2bSuE9KgVbDajdhi15QgwMkRIeuJg',
    appId: '1:375449913411:android:66264e7b69cecc3ab0ecf6',
    messagingSenderId: '375449913411',
    projectId: 'faraxda',
    storageBucket: 'faraxda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkxHd4JXiDGmlM6puKfCwMQmm2DeuY7fE',
    appId: '1:375449913411:ios:57f3f2d8008c9952b0ecf6',
    messagingSenderId: '375449913411',
    projectId: 'faraxda',
    storageBucket: 'faraxda.firebasestorage.app',
    iosBundleId: 'com.yourcompany.farxada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkxHd4JXiDGmlM6puKfCwMQmm2DeuY7fE',
    appId: '1:375449913411:ios:6859e6cb3ee6f43fb0ecf6',
    messagingSenderId: '375449913411',
    projectId: 'faraxda',
    storageBucket: 'faraxda.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );
}
